---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: podinfo
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./apps/election-app/kustomization.yaml
  prune: true
  sourceRef:
    kind: GitRepository
    name: election-app
  targetNamespace: default

