apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: sonarqube
  namespace: flux-system
spec:
  interval: 5m0s
  path: ./infrastructure/tools/sonarqube/kustomization.yaml
  prune: true
  sourceRef:
    kind: GitRepository
    name: election-app
  targetNamespace: sonarqube
