apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sonarqube
  namespace: sonarqube
spec:
  interval: 5m
  chart:
    spec:
      chart: sonarqube
      version: '9.5.0'
      sourceRef:
        kind: HelmRepository
        name: sonarqube
        namespace: sonarqube
      interval: 1m
  values:
    replicaCount: 1
    
