apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sonarqube
  namespace: sonarqube
spec:
  chart:
    spec:
      chart: sonarqube | bitnami/sonarqube
      sourceRef:
        kind: HelmRepository
        name: sonarqube
        namespace: flux-system
      version: 2.1.5
  interval: 1m0s
