apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: sonarqube
  namespace: flux-system
spec:
  interval: 1m
  url: https://charts.bitnami.com/bitnami



---

apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sonarqube
  namespace: sonarqube
spec:
  chart:
    spec:
      chart: my-sonarqube | bitnami/sonarqube
      sourceRef:
        kind: HelmRepository
        name: starboard-operator
        namespace: flux-system
      version: 2.1.15
  interval: 1m0s


