apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: docker-registry
  namespace: flux-system
spec:
  chart:
    spec:
      chart: docker-registry
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: docker-registry
  interval: 5m0s
  releaseName: docker-registry
  values:
    service:
      name: registry
      type: LoadBalancer
    replicaCount: 1
    persistence:
      enabled: true
      size: 60Gi
      deleteEnabled: true
      storageClass: default  
    secrets:
      htpasswd: abdelhakavaxia:$2y$05$gCNFEF7to2BF1FseQfZjtO3bpMNbDXyR7NHAwWkRHW3YIrgeQzbwu  
  targetNamespace: docker-registry
