apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sonarqube
  namespace: flux-system
spec:
  chart:
    spec:
      chart: sonarqube
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: bitnami
  interval: 5m0s
  releaseName: sonarqube
  values:
    imagePullPolicy: Always
  targetNamespace: abdelhak
