apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: harbor
  namespace: flux-system
spec:
  chart:
    spec:
      chart: harbor #
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: bitnami
  interval: 5m0s
  releaseName: harbor
  values:
    global:
      storageClass: default
    adminPassword: admin
    
         
  targetNamespace: harbor
