apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: harbor
  namespace: flux-system
spec:
  chart:
    spec:
      chart: harbor #
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: harbor
  interval: 5m0s
  releaseName: harbor
  values:
    expose:
      type: loadBalancer
      tls:
        enabled: false
    persistence:
      enabled: false
    harborAdminPassword: admin

         
  targetNamespace: harbo
