apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sonarqube
  namespace: flux-system
spec:
  chart:
    spec:
      chart: sonarqube
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        name: bitnami
  interval: 5m0s
  releaseName: sonarqube
  values:
    sonarqubePassword:
         secretKeyRef:
              name: sonar-secret
              key: pass  
    image: 
      pullPolicy: Always
    persistence:
      enabled: true
      storageClass: default 
    postgresql:
      persistence:
          storageClass: default         
  targetNamespace: abdelhak 
